### ISSUE TITLE
order pcb panelized

### ISSUE THREAD

**Issue by Sebbes22** [RalphBacon/235_KCX_BT_EMITTER-Breakout-Board#2]
Hi,

I wanted to order some break out boards for the KCX_BT_EMITTER and so I imported your provided files to JLCPCB.
In the preview of the order I realized that there are outlines for the panelized boards but only one of the four boards was completely visible (see attached photo). 
Is this because of your provided files or am I making a mistake importing the files to JLCPCB?

Best regards
Sebbes22

![PCB](https://user-images.githubusercontent.com/40956835/201470944-df818455-1d54-4e28-b95a-3475e0accda7.PNG)

**Comment by RalphBacon** [comment]
This is correct. 

It worried me a bit when I originally submitted it, but as it says at the top of the Gerber image, it is recognised by all PCB fabs as a panelised board.

Good luck with your project!
